# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8086
    connection-timeout: 5000
    session: 
       timeout: 7200
    context-path: /zzg

rcsysconfig:
  token:
    expire: 360

spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/views/
    #禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
    thymeleaf:
        cache: false
        cache-period: 0
        template:  
           cache: false
    #添加那个目录的文件需要restart
    devtools:
          #热部署生效
          enabled: true
          restart:
          #添加那个目录的文件需要restart
          additional-paths: src/main/java
          #排除那个目录的文件不需要restart
          exclude: src/main/resources/views/**,src/main/resources/static/**
          
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml

jwtconfig:
    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: f4e2e52332348f86b6256e581c0f9eb5
        # token有效时长，7天，单位秒
        expire: 604800
        header: token

